// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BironextWordpressIntegrationHub.structs
{

    public class WoocommerceCoupon
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("amount")]
        public string Amount { get; set; }

        [JsonProperty("date_created")]
        public DateCreated DateCreated { get; set; }

        [JsonProperty("date_modified")]
        public DateModified DateModified { get; set; }

        [JsonProperty("date_expires")]
        public object DateExpires { get; set; }

        [JsonProperty("discount_type")]
        public string DiscountType { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("usage_count")]
        public int UsageCount { get; set; }

        [JsonProperty("individual_use")]
        public bool IndividualUse { get; set; }

        [JsonProperty("product_ids")]
        public IList<object> ProductIds { get; set; }

        [JsonProperty("excluded_product_ids")]
        public IList<object> ExcludedProductIds { get; set; }

        [JsonProperty("usage_limit")]
        public int UsageLimit { get; set; }

        [JsonProperty("usage_limit_per_user")]
        public int UsageLimitPerUser { get; set; }

        [JsonProperty("limit_usage_to_x_items")]
        public object LimitUsageToXItems { get; set; }

        [JsonProperty("free_shipping")]
        public bool FreeShipping { get; set; }

        [JsonProperty("product_categories")]
        public IList<object> ProductCategories { get; set; }

        [JsonProperty("excluded_product_categories")]
        public IList<object> ExcludedProductCategories { get; set; }

        [JsonProperty("exclude_sale_items")]
        public bool ExcludeSaleItems { get; set; }

        [JsonProperty("minimum_amount")]
        public string MinimumAmount { get; set; }

        [JsonProperty("maximum_amount")]
        public string MaximumAmount { get; set; }

        [JsonProperty("email_restrictions")]
        public IList<object> EmailRestrictions { get; set; }

        [JsonProperty("used_by")]
        public IList<string> UsedBy { get; set; }

        [JsonProperty("virtual")]
        public bool Virtual { get; set; }

        [JsonProperty("meta_data")]
        public IList<object> MetaData { get; set; }
    }

}
